# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38bae493e5ec0d990b3c5bd372bf6b0fe1ccea986c41b79155f924d28cfb6e03f5d6fad065f8038d6feaa695f3fdbede4a44c53cf1daab7c2e721ac5b9c17dc

test:
  secret_key_base: b9f94239517b9710e5d04733337baa3dc74ace476064992e8b61c205b16cabb8efee065c311a1527c3eba054156b55473caa1b8229b053f566312723fc78e5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
